//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicOnDemand
{
    using System;
    using System.Collections.Generic;
    
    public partial class država
    {
        public država()
        {
            this.izvođač = new HashSet<izvođač>();
        }
    
        public int državaID { get; set; }
        public string nazivDržave { get; set; }
    
        public virtual ICollection<izvođač> izvođač { get; set; }
    }
}
