//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicOnDemand
{
    using System;
    using System.Collections.Generic;
    
    public partial class pjesma
    {
        public int pjesmaID { get; set; }
        public int albumID { get; set; }
        public int žanrID { get; set; }
        public string nazivPjesme { get; set; }
        public Nullable<System.TimeSpan> vrijemeTrajanja { get; set; }
    
        public virtual album album { get; set; }
        public virtual žanr žanr { get; set; }
    }
}
