//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicOnDemand
{
    using System;
    using System.Collections.Generic;
    
    public partial class žanr
    {
        public žanr()
        {
            this.album = new HashSet<album>();
            this.album1 = new HashSet<album>();
            this.pjesma = new HashSet<pjesma>();
            this.izvođač = new HashSet<izvođač>();
        }
    
        public int žanrID { get; set; }
        public string nazivŽanra { get; set; }
    
        public virtual ICollection<album> album { get; set; }
        public virtual ICollection<album> album1 { get; set; }
        public virtual ICollection<pjesma> pjesma { get; set; }
        public virtual ICollection<izvođač> izvođač { get; set; }
    }
}
